// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbtJdeLMFZydsZRBhzDp6HvWklwuxQnas',
    appId: '1:333438066571:web:9488a4643caed6fb85598e',
    messagingSenderId: '333438066571',
    projectId: 'bumilku-e9cd8',
    authDomain: 'bumilku-e9cd8.firebaseapp.com',
    storageBucket: 'bumilku-e9cd8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkKxXuwWtZcf2dD8jVI2wqILElgLxIL5M',
    appId: '1:333438066571:android:f447e97eb49cf0c785598e',
    messagingSenderId: '333438066571',
    projectId: 'bumilku-e9cd8',
    storageBucket: 'bumilku-e9cd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdCCIqSjvh4u4a4EiuhCKslmr77zpemz0',
    appId: '1:333438066571:ios:49675982b42b533385598e',
    messagingSenderId: '333438066571',
    projectId: 'bumilku-e9cd8',
    storageBucket: 'bumilku-e9cd8.firebasestorage.app',
    iosBundleId: 'com.gloriyan.bumilkuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdCCIqSjvh4u4a4EiuhCKslmr77zpemz0',
    appId: '1:333438066571:ios:49675982b42b533385598e',
    messagingSenderId: '333438066571',
    projectId: 'bumilku-e9cd8',
    storageBucket: 'bumilku-e9cd8.firebasestorage.app',
    iosBundleId: 'com.gloriyan.bumilkuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbtJdeLMFZydsZRBhzDp6HvWklwuxQnas',
    appId: '1:333438066571:web:d262ae728de7b5aa85598e',
    messagingSenderId: '333438066571',
    projectId: 'bumilku-e9cd8',
    authDomain: 'bumilku-e9cd8.firebaseapp.com',
    storageBucket: 'bumilku-e9cd8.firebasestorage.app',
  );
}
